---

- name: disable swap now
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: permanently disable swap
  mount:
    name: swap
    fstype: swap
    state: absent

- name: set ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.conf

- name: ensure net bridge for ipv4
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.conf

- name: ensure net bridge for ipv6
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.conf

- name: put selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

#- name: adjust firewall rules
   

#- name: modprobe br_netfilter
#- name: setup kubernetes rpm repos

- name: install kubelet package
  yum: 
    name: kubelet
    state: present

- name: install kubeadm package
  yum: 
    name: kubeadm
    state: present

- name: install kubectl package
  yum: 
    name: kubectl
    state: present

- name: enable kubelet service
  systemd:
    name: kubelet
    enabled: yes

- name: install jq package
  yum:
    name: jq
    state: present

- name: install nfs-utils package
  yum:
    name: nfs-utils
    state: present

- name: create kubernetes certs directory
  file: 
    path: /root/.kube/certs
    state: directory
    mode: '0755'

- name: mount certs
  mount:
    path: /root/.kube/certs
    src: 192.168.56.102:/certs
    fstype: nfs 
    opts: defaults
    state: present



###add kubernetes user?????
###add firewall rules
####mount kubernetes tarball nfs share
