---

- name: set ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.conf

- name: ensure net bridge for ipv4
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.conf

- name: ensure net bridge for ipv6
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.conf

- name: put selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

#- name: modprobe br_netfilter
#- name: setup kubernetes rpm repos

- name: install kubelet package
  yum: 
    name: kubelet
    state: present

- name: install kubeadm package
  yum: 
    name: kubeadm
    state: present

- name: install kubectl package
  yum: 
    name: kubectl
    state: present

- name: enable kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: yes

###add kubernetes user?????
###add firewall rules
####mount kubernetes tarball nfs share
