---

- name: register kubernetes images
  find: 
    paths: /kubernetes-images
    patterns: "*.tar"
  register: kubernetes_images

- name: load kubernetes images
  command: "docker load < {{ item.path }}"
  with_items: "{{ kubernetes_images }}"