---
- name: initialize kubernetes master
  command: >
    kubeadm init 
    --pod-network-cidr=10.244.0.0/16
    --apiserver-advertise-address 192.168.56.101 
    --apiserver-bind-port 644
  register: kubeadmin_init
  failed_when: false
  when: not kubernetes_init_stat.stat.exists

- name: symlink kubectl admin.conf to /root/.kube/conf
  file:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    state: link

- name: set path for kubeconfig
  environment: 
    KUBECONFIG: "/root/.kube/conf"

- name: create kubernetes-offline directory
  file: 
    path: /opt/kubernetes-offline
    state: directory
    mode: '0755'
  
- name: lay down kube flannel yaml
  template:
    src: /templates/kube-flannel.yml.j2
    dest: /opt/kubernetes-offline/kube-flannel.yml
    owner: root
    group: root
    mode: '770'

- name: configure flannel networking
  command: "{{ item }}"
  with_items:
    - kubectl apply -f /opt/kubernetes-offline/kube-flannel.yaml
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"

- name: taint status
  command: "{{ item }}"
  with_items:
    - kubectl get nodes -o json | jq '.items[].spec.taints'
  register: taint_status

- name: untaint master node
  command: "{{ item }}"
  with_items:
    - kubectl taint nodes --all node-role.kubernetes.io/master-
  when: taint_status != null





