#first command 
kubeadm init --pod-network-cidr=10.244.0.0/16

#second
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml

#third
kubectl taint nodes --all node-role.kubernetes.io/master-



####notes
this can pull images beforehand:
kubeadm config images pull